name: Update README
on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Update README
      uses: npalm/action-docs-action@v1.1.0
      with:
        readme: ./README.md
        actionFile: ./action.yml
        tocLevel: 2
        lineBreaks: LF

    - name: commit and push
      uses: stefanzweifel/git-auto-commit-action@v4.9.0
      with: 
        commit_message: "Auto-update README.md"
        branch: "update-readme"
        push_options: '--force'
